hebbible.usage.database=postgres

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/hebbible}
spring.datasource.username=${POSTGRES_USER:hebbible}
spring.datasource.password=${POSTGRES_PASSWORD:hebbible}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.locations=classpath:db/migration/postgres
