spring.application.name=psukim

#server.port=8090

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

hebbible.usage.database=sqlite
hebbible.usage.sqlite.path=usage.db

spring.datasource.url=jdbc:sqlite:${hebbible.usage.sqlite.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.flyway.locations=classpath:db/migration/${hebbible.usage.database}
spring.flyway.baseline-on-migrate=true

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/${hebbible.usage.database}/db.changelog-master.xml

logging.level.org.flywaydb=INFO
logging.level.liquibase=INFO
