name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit Tests and generate coverage report
        run: |
          cd python
          pytest tests
